
# - name: This is main file for Project "Sandbox_Environemnt"
#   hosts: localhost
#   connection: local
#   become: true
#   gather_facts: yes
#   vars:
#     ansible_python_interpreter: /opt/hostedtoolcache/Python/3.10.19/x64/bin/python
#   roles:
#     - sandbox_environemnt


- name: Infrastructure vm_creation
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    number_of_sandboxes: 3        
    base_rg_name: "M-sandbox-rg"
    location: "eastus"
