- name: This is main file for Project "Sandbox_Environemnt"
  hosts: localhost
  connection: local
  become: true
  gather_facts: yes
  vars:
    ansible_python_interpreter: /opt/hostedtoolcache/Python/3.10.19/x64/bin/python
    rg_count: "{{ lookup('env','RG_COUNT') | int }}"
    rg_base_name: "{{ lookup('env','RG_BASE_NAME') }}"
  roles:
    - sandbox_environemnt