
# - name: This is main file for Project "Sandbox_Environemnt"
#   hosts: localhost
#   connection: local
#   become: true
#   gather_facts: yes
#   vars:
#     ansible_python_interpreter: /opt/hostedtoolcache/Python/3.10.19/x64/bin/python
#   roles:
#     - sandbox_environemnt


- name: Infrastructure vm_creation
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    number_of_sandboxes: 3        
    base_rg_name: "M-sandbox-rg"
    location: "eastus"

- name: Generate resource_groups_list dynamically
  set_fact:
    resource_groups_list: >-
      {{
        range(1, number_of_sandboxes + 1) | map('int') | map('regex_replace', '^(.*)$', 
          '{ "name": "' ~ base_rg_name ~ '-\\1", "location": "' ~ location ~ '", "vnet_name": "sandbox-vnet-\\1", "subnet": "subnet\\1", "address_prefixes_vnet": "10.' ~ ((\\1 | int) -1) ~ '.0.0/16", "address_prefixes_subnet": "10.' ~ ((\\1 | int) -1) ~ '.0.0/24", "NIC_name": "nic\\1", "Ip_name": "ip\\1", "vm_name": "vm\\1", "vm_size": "Standard_B1s", "admin_username": "azureuser", "storage": "stg\\1" }'
        ) | list
      }}

- name: Create resources for each sandbox
  include_tasks: sandbox_tasks.yml
  loop: "{{ resource_groups_list }}"
  loop_control:
    loop_var: item
